import "~/styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { Logo, Navbar } from "~/components/navbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Supermemory",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`min-h-screen bg-[#171B1F] font-sans antialiased ${fontSans.variable}`}
    >
      <body>
        <main>
          <Logo />
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
